# Generated by Django 5.0.2 on 2024-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apllica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
